import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';
const isProduction = process.env.NEXT_PUBLIC_V2_PRODUCTION === 'true';
const channelCandidate = process.env.NEXT_PUBLIC_WHATSAPP_CHANNEL_URL?.trim();
const whatsappChannel = channelCandidate && /^https:\/\/whatsapp\.com\/channel\/[a-zA-Z0-9]+\/?$/.test(channelCandidate) ? channelCandidate : null;
export const metadata: Metadata = { metadataBase: new URL(isProduction ? 'https://navvyasignal.com' : 'https://navvyasignal-v2-preview.netlify.app'), title: { default: 'NavvyaSignal — Global Intelligence', template: '%s | NavvyaSignal' }, description: 'Independent global intelligence, analysis and cross-desk reporting.', robots: { index: isProduction, follow: isProduction } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
 return <html lang="en"><body><header className="mast"><div className="container"><Link href="/" className="brand">NAVVYA<span>SIGNAL</span><small>INDEPENDENT GLOBAL INTELLIGENCE</small></Link><nav><Link href="/">Home</Link><Link href="/signals">Signals</Link><Link href="/watchlist">Watchlist</Link><Link href="/network">Network</Link><a href="/#desks">Desks</a><Link href="/about">About</Link></nav></div></header>{children}<footer className="footer"><div className="container footer-inner"><div><strong>NAVVYASIGNAL</strong><p>Independent global intelligence</p>{!isProduction && <small>V2 preview · Production remains on Framer.</small>}</div><nav aria-label="Information and policies"><Link href="/about">About Us</Link><Link href="/methodology">Methodology</Link><Link href="/editorial-ai-policy">Editorial &amp; AI Policy</Link><Link href="/contact">Contact Us</Link><Link href="/network">The Navvya Network</Link><Link href="/old-archives-v1">Old Archives — Version 1</Link><a href="mailto:hello@navvyasignal.com?subject=Daily%20Brief%20subscription%20request">Subscribe to Daily Brief</a>{whatsappChannel && <a href={whatsappChannel} target="_blank" rel="noopener noreferrer">Join our WhatsApp Channel ↗</a>}<a href="mailto:hello@navvyasignal.com">hello@navvyasignal.com</a><div className="footer-social" aria-label="Share NavvyaSignal"><a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fnavvyasignal.com" target="_blank" rel="noopener noreferrer">Share on LinkedIn ↗</a><a href="https://twitter.com/intent/tweet?url=https%3A%2F%2Fnavvyasignal.com" target="_blank" rel="noopener noreferrer">Share on X ↗</a><a href="https://api.whatsapp.com/send?text=https%3A%2F%2Fnavvyasignal.com" target="_blank" rel="noopener noreferrer">Share on WhatsApp ↗</a></div></nav></div></footer></body></html>;
}
